#!/bin/bash
#SBATCH -J thclean_array
#SBATCH -A lt200258
#SBATCH -p gpu-limited
#SBATCH -N 1
#SBATCH --gpus=4 
#SBATCH -c 64
#SBATCH --mem=200G
#SBATCH -t 02:00:00
#SBATCH -o logs/%x.%A_%a.out
#SBATCH -e logs/%x.%A_%a.err

set -euo pipefail
mkdir -p logs

# ===== Modules / Conda env =====
module purge || true
module restore || true
ml Mamba || true
conda activate /lustrefs/disk/project/lt200258-aithai/QP/cleaning_pipeline/llm_data_cleaning_project/text_cleaning_utils/notebooks/env
PYTHON='/lustrefs/disk/project/lt200258-aithai/QP/cleaning_pipeline/llm_data_cleaning_project/text_cleaning_utils/notebooks/env/bin/python'
# ===== Runtime env =====
export HF_HOME="${HF_HOME:-/lustrefs/disk/project/lt200258-aithai/.cache/huggingface}"
export THAI_NER_PATH="/model/models--loolootech--no-name-ner-th"
export HF_HUB_OFFLINE=1
export CUDA_VISIBLE_DEVICES="" 
export TRANSFORMERS_OFFLINE=1
export TRANSFORMERS_NO_ADVISORY_WARNINGS=1
export TRANSFORMERS_VERBOSITY=error
export TOKENIZERS_PARALLELISM=false
export TF_CPP_MIN_LOG_LEVEL=3
# ===== Pipeline & knobs =====
#กรณีใส่ path เป็น dir ให้ใช้ --pattern "*.jsonl" 
IN="/project/lt200393-foullm/QP/benchmark_v4.jsonl"            # โฟลเดอร์ต้นทาง
OUT="/project/lt200393-foullm/QP/runs"          # โฟลเดอร์ปลายทาง
SCRIPT="/project/lt200393-foullm/QP/Pipeline_clean.py"   # แนะนำ: เปลี่ยนชื่อไฟล์ให้ไม่มีช่องว่าง
FASTTEXT="/model/fasttext.bin"            # ถ้าไม่ใช้ fastText ให้คอมเมนต์ทิ้ง
PF_FILES="corpus/thai_celeb_list.txt,corpus/thai_public_figure_new.txt"

export FT_LABEL_LEGAL="__label__0"
export FT_LABEL_ILLEGAL="__label__1"

srun "$PYTHON" "$SCRIPT" \
  -i "$IN" \
  -o "$OUT" \
  --workers 32 \
  --chunk-size 50000 \
  --public-figure-files "$PF_FILES" \
  --thai-ner-full \
  --thai-ner-policy anonymize \
  --thai-ner-cats PERSON,PHONE,EMAIL,ADDRESS,NATIONAL_ID \
  --fasttext-model "$FASTTEXT" \
  --flags-key "flags" \
  --thai-mark-fix \
  --floating-policy drop \
  --normalize NFC \
  --clear-ckpt
echo "[DONE] outputs at: $OUT"
